[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:LJFRIESE/nvim.git"
    refreshPeriod = "24h"
["git/.oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["git/.oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
["git/zsh-autocomplete"]
	type = "archive"
	url = "https://github.com/marlonrichert/zsh-autocomplete/archive/main.tar.gz"
	exact = true
	stripComponents = 1
