[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:LJFRIESE/nvim.git"
    refreshPeriod = "1h"
["git/oh-my-tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux"
    stripComponents = 1
["git/.oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh"
    stripComponents = 1
["git/.oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k"
    stripComponents = 1
["git/zsh-autocomplete"]
	type = "git-repo"
	url = "https://github.com/marlonrichert/zsh-autocomplete"
	stripComponents = 1
